// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnag3_oYu-B-ISWwManAF4gSMQ-pON35c',
    appId: '1:509460773140:web:37d50419a1800e78fa2a01',
    messagingSenderId: '509460773140',
    projectId: 'univy-push',
    authDomain: 'univy-push.firebaseapp.com',
    storageBucket: 'univy-push.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2fc7f-g0uzskuTIxNISYdn4BMSuj-QAw',
    appId: '1:509460773140:android:9b826dc5ea089d6dfa2a01',
    messagingSenderId: '509460773140',
    projectId: 'univy-push',
    storageBucket: 'univy-push.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq44_buDS4dDmreG0rdI-2oJmWEcdX3DE',
    appId: '1:509460773140:ios:7e15b4b081a55ff4fa2a01',
    messagingSenderId: '509460773140',
    projectId: 'univy-push',
    storageBucket: 'univy-push.firebasestorage.app',
    iosBundleId: 'com.example.eaAppG5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq44_buDS4dDmreG0rdI-2oJmWEcdX3DE',
    appId: '1:509460773140:ios:7e15b4b081a55ff4fa2a01',
    messagingSenderId: '509460773140',
    projectId: 'univy-push',
    storageBucket: 'univy-push.firebasestorage.app',
    iosBundleId: 'com.example.eaAppG5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnag3_oYu-B-ISWwManAF4gSMQ-pON35c',
    appId: '1:509460773140:web:6b87bf4218de02e9fa2a01',
    messagingSenderId: '509460773140',
    projectId: 'univy-push',
    authDomain: 'univy-push.firebaseapp.com',
    storageBucket: 'univy-push.firebasestorage.app',
  );
}
